apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : spam2000
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: local
  source:
    path   : "charts/spam2000"
    repoURL: "https://github.com/Alex21022001/spam2000-infra"
    targetRevision: "main"
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
