{
 "title": "Spam2000v1",
 "tags": [ "spam2000" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Application", "query": "spam2000" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(name_gauge{container=\"$Application\"},namespace)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(name_gauge{container=\"$Application\", namespace=\"$Namespace\"},instance)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(name_gauge{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\"},pod)"
    }
   },
   {
    "name": "Source",
    "query": "random_gauge_1,random_gauge_2,random_gauge_3"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (email) (last_over_time(name_gauge{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Country by Activity",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (country) (last_over_time($Source{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__range])))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Top 10 Platform by Activity",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (platform) (last_over_time($Source{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__range])))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Top 10 Product by Activity",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (product) (last_over_time($Source{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__range])))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Top 10 Jobs by Activity",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (exported_job) (last_over_time(name_gauge{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__range])))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Average Ordered Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(ordered_histogram_sum{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__rate_interval])) \n/ \nsum(rate(ordered_histogram_count{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "P99 Latency: Ordered Operations",
   "type": "timeseries",
   "description": "This chart calculates the value below which 99% of the observations fall",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ordered_histogram_bucket{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__rate_interval])))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Orders Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ordered_histogram_count{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "P90 Latency: Ordered Operations",
   "type": "timeseries",
   "description": "This chart calculates the value below which 90% of the observations fall",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(ordered_histogram_bucket{container=\"$Application\", namespace=\"$Namespace\", instance=~\"$Instance\", pod=~\"$Pod\"}[$__rate_interval])))",
     "legendFormat": "value"
    }
   ]
  }
 ]
}