apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: "${namespace}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: "${namespace}"
  source:
    repoURL       : "${repoURL}"
    path          : "${path}"
    targetRevision: "${targetRevision}"
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
